
# Author: Ben Langmead
#   Date: 5/31/2018

FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y gdb
RUN apt-get install -y valgrind
RUN apt-get install -y emacs-nox
RUN apt-get install -y git
RUN apt-get install -y libtbb-dev libtbb2
RUN apt-get install -y zlib1g zlib1g-dev
RUN apt-get install -y make
