# Author: Ben Langmead
#   Date: 5/31/2018

FROM centos:7

RUN yum update -y
RUN yum install -y valgrind
RUN yum install -y gdb
RUN yum install -y gcc
RUN yum install -y gcc-c++
RUN yum install -y emacs-nox
RUN yum install -y git
RUN yum install -y tbb-devel
RUN yum install -y zlib-devel
RUN yum install -y make
